apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: scaleway-secret-store
spec:
  provider:
    scaleway:
      region: fr-par
      projectId: "${SCW_DEFAULT_PROJECT_ID}"
      accessKey:
        secretRef:
          name: scaleway-api-credentials
          namespace: external-secrets
          key: access-key
      secretKey:
        secretRef:
          name: scaleway-api-credentials
          namespace: external-secrets
          key: secret-key
