apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: sovereign-wisdom
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-store
  target:
    name: db-credentials
  data:
    - secretKey: db-password
      remoteRef:
        key: "name:dev-db-password"
        version: latest_enabled
