apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sovereign-wisdom
data:
  db-host: "${DB_ENDPOINT_IP}"
  db-port: "${DB_ENDPOINT_PORT}"
  db-name: "app"
  db-user: "app_admin"
