apiVersion: v1
kind: Service
metadata:
  name: sovereign-wisdom
  namespace: sovereign-wisdom
  labels:
    app: sovereign-wisdom
spec:
  type: ClusterIP
  selector:
    app: sovereign-wisdom
  ports:
    - port: 8000
      targetPort: 8000
